### ISSUE TITLE
数据库初始化脚本提供一下

### ISSUE THREAD

**Issue by zyclove** [ChengYingOpenSource/wucaishi#4]

**Comment by zyclove** [comment]
操作用户手册也还没有吗？最近怎么没有更新了？

**Comment by WhatAKitty** [comment]
已经增加。
用户手册请看wiki https://github.com/ChengYingOpenSource/wucaishi/wiki
部署手册：https://github.com/ChengYingOpenSource/wucaishi/wiki/%E9%83%A8%E7%BD%B2%E6%8C%87%E5%BC%95
